import React, { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { apiService } from "@/services/api";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import {
  Building2,
  User,
  MapPin,
  Phone,
  Mail,
  DollarSign,
  Save,
  X,
} from "lucide-react";

interface Department {
  code?: string; // Optional - will be auto-generated
  name: string;
  description?: string;
  head?: string; // User ID
  location?: string;
  phone?: string;
  email?: string;
  staffCount: number;
  budget: number;
  status: "active" | "inactive";
}

interface AddDepartmentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (department: Department) => void;
}

const AddDepartmentModal: React.FC<AddDepartmentModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
}) => {
  const { t } = useTranslation();
  const [formData, setFormData] = useState<Department>({
    code: "",
    name: "",
    description: "",
    head: "",
    location: "",
    phone: "",
    email: "",
    staffCount: 0,
    budget: 0,
    status: "active",
  });

  const [errors, setErrors] = useState<Partial<Department>>({});
  const [doctors, setDoctors] = useState<any[]>([]);
  const [loadingDoctors, setLoadingDoctors] = useState(false);

  // Fetch doctors when modal opens
  useEffect(() => {
    if (isOpen) {
      fetchDoctors();
    }
  }, [isOpen]);

  const fetchDoctors = async () => {
    try {
      setLoadingDoctors(true);
      const response = await apiService.getUsers({
        role: "doctor",
        limit: 100,
        is_active: true
      });
      if (response.success && response.data && response.data.users) {
        setDoctors(response.data.users);
      } else {
        setDoctors([]);
      }
    } catch (error) {
      console.error("Error fetching doctors:", error);
      setDoctors([]);
    } finally {
      setLoadingDoctors(false);
    }
  };

  const handleInputChange = (
    field: keyof Department,
    value: string | number,
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));

    // Clear error when user starts typing
    if (errors[field]) {
      setErrors((prev) => ({
        ...prev,
        [field]: undefined,
      }));
    }
  };

  // Department code will be auto-generated by backend, so we don't need to generate it here
  // But we can still allow manual entry if needed

  const validateForm = () => {
    const newErrors: Partial<Department> = {};

    // Only name is required
    if (!formData.name.trim()) {
      newErrors.name = t("Department name is required");
    }

    // Optional fields validation - only validate format if provided
    if (formData.email && formData.email.trim() && !/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = t("Please enter a valid email address");
    }

    if (formData.budget < 0) {
      newErrors.budget = t("Budget cannot be negative");
    }

    if (formData.staffCount < 0) {
      newErrors.staffCount = t("Staff count cannot be negative");
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = () => {
    if (validateForm()) {
      // Only send fields that have values (except name which is required)
      const submitData: Department = {
        name: formData.name,
        status: formData.status,
        staffCount: formData.staffCount,
        budget: formData.budget,
        ...(formData.code && formData.code.trim() && { code: formData.code }),
        ...(formData.description && formData.description.trim() && { description: formData.description }),
        ...(formData.head && formData.head.trim() && { head: formData.head }),
        ...(formData.location && formData.location.trim() && { location: formData.location }),
        ...(formData.phone && formData.phone.trim() && { phone: formData.phone }),
        ...(formData.email && formData.email.trim() && { email: formData.email }),
      };
      onSubmit(submitData);
      handleClose();
    }
  };

  const handleClose = () => {
    setFormData({
      code: "",
      name: "",
      description: "",
      head: "",
      location: "",
      phone: "",
      email: "",
      staffCount: 0,
      budget: 0,
      status: "active",
    });
    setErrors({});
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <Building2 className="h-6 w-6 mr-3 text-blue-600" />
            {t("Add New Department")}
          </DialogTitle>
          <DialogDescription>
            {t("Create a new department with all necessary information and settings.")}
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="basic" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="basic">{t("Basic Information")}</TabsTrigger>
            <TabsTrigger value="contact">{t("Contact & Location")}</TabsTrigger>
            <TabsTrigger value="management">{t("Management")}</TabsTrigger>
          </TabsList>

          {/* Basic Information Tab */}
          <TabsContent value="basic" className="space-y-6">
            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="code">{t("Department Code")} (Optional)</Label>
                <Input
                  id="code"
                  placeholder={t("Auto-generated if left empty")}
                  value={formData.code || ""}
                  onChange={(e) =>
                    handleInputChange("code", e.target.value.toUpperCase())
                  }
                  className={errors.code ? "border-red-500" : ""}
                  maxLength={10}
                />
                {errors.code && (
                  <p className="text-sm text-red-600">{errors.code}</p>
                )}
                <p className="text-xs text-gray-500">
                  {t("Leave empty to auto-generate (e.g., DEPT001, DEPT002)")}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="status">{t("Status")} *</Label>
                <Select
                  value={formData.status}
                  onValueChange={(value: "active" | "inactive") =>
                    handleInputChange("status", value)
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">{t("Active")}</SelectItem>
                    <SelectItem value="inactive">{t("Inactive")}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="name">{t("Department Name")} *</Label>
              <Input
                id="name"
                placeholder={t("e.g., Cardiology, Neurology, Pediatrics")}
                value={formData.name}
                onChange={(e) => handleInputChange("name", e.target.value)}
                className={errors.name ? "border-red-500" : ""}
              />
              {errors.name && (
                <p className="text-sm text-red-600">{errors.name}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">{t("Description")} (Optional)</Label>
              <Textarea
                id="description"
                placeholder={t("Brief description of the department's role and services...")}
                value={formData.description || ""}
                onChange={(e) =>
                  handleInputChange("description", e.target.value)
                }
                className={errors.description ? "border-red-500" : ""}
                rows={4}
              />
              {errors.description && (
                <p className="text-sm text-red-600">{errors.description}</p>
              )}
            </div>
          </TabsContent>

          {/* Contact & Location Tab */}
          <TabsContent value="contact" className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="location">{t("Location")} (Optional)</Label>
              <div className="relative">
                <MapPin className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  id="location"
                  placeholder={t("e.g., Building A, Floor 3, Room 301")}
                  value={formData.location || ""}
                  onChange={(e) =>
                    handleInputChange("location", e.target.value)
                  }
                  className={`pl-10 ${errors.location ? "border-red-500" : ""}`}
                />
              </div>
              {errors.location && (
                <p className="text-sm text-red-600">{errors.location}</p>
              )}
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="phone">{t("Phone Number")} (Optional)</Label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                  <Input
                    id="phone"
                    placeholder={t("+1 (555) 123-4567")}
                    value={formData.phone || ""}
                    onChange={(e) => handleInputChange("phone", e.target.value)}
                    className={`pl-10 ${errors.phone ? "border-red-500" : ""}`}
                  />
                </div>
                {errors.phone && (
                  <p className="text-sm text-red-600">{errors.phone}</p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">{t("Email Address")} (Optional)</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                  <Input
                    id="email"
                    type="email"
                    placeholder={t("department@clinicpro.com")}
                    value={formData.email || ""}
                    onChange={(e) => handleInputChange("email", e.target.value)}
                    className={`pl-10 ${errors.email ? "border-red-500" : ""}`}
                  />
                </div>
                {errors.email && (
                  <p className="text-sm text-red-600">{errors.email}</p>
                )}
              </div>
            </div>
          </TabsContent>

          {/* Management Tab */}
          <TabsContent value="management" className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="head">{t("Department Head")} (Optional)</Label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 z-10" />
                <Select
                  value={formData.head || undefined}
                  onValueChange={(value) => handleInputChange("head", value)}
                >
                  <SelectTrigger className={`pl-10 ${errors.head ? "border-red-500" : ""}`}>
                    <SelectValue placeholder={t("Select a doctor (Optional)")} />
                  </SelectTrigger>
                  <SelectContent>
                    {loadingDoctors ? (
                      <div className="px-2 py-1.5 text-sm text-muted-foreground">{t("Loading doctors...")}</div>
                    ) : doctors.length === 0 ? (
                      <div className="px-2 py-1.5 text-sm text-muted-foreground">{t("No doctors available")}</div>
                    ) : (
                      doctors.map((doctor) => (
                        <SelectItem key={doctor._id} value={doctor._id}>
                          {doctor.first_name} {doctor.last_name} {doctor.email ? `(${doctor.email})` : ''}
                        </SelectItem>
                      ))
                    )}
                  </SelectContent>
                </Select>
              </div>
              {errors.head && (
                <p className="text-sm text-red-600">{errors.head}</p>
              )}
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="staffCount">{t("Current Staff Count")}</Label>
                <Input
                  id="staffCount"
                  type="number"
                  min="0"
                  placeholder={t("0")}
                  value={formData.staffCount || ""}
                  onChange={(e) =>
                    handleInputChange(
                      "staffCount",
                      parseInt(e.target.value) || 0,
                    )
                  }
                  className={errors.staffCount ? "border-red-500" : ""}
                />
                {errors.staffCount && (
                  <p className="text-sm text-red-600">{errors.staffCount}</p>
                )}
                <p className="text-xs text-gray-500">
                  {t("Number of staff members currently assigned to this department")}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="budget">{t("Annual Budget (USD)")}</Label>
                <div className="relative">
                  <DollarSign className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                  <Input
                    id="budget"
                    type="number"
                    min="0"
                    step="1000"
                    placeholder={t("500000")}
                    value={formData.budget || ""}
                    onChange={(e) =>
                      handleInputChange("budget", parseInt(e.target.value) || 0)
                    }
                    className={`pl-10 ${errors.budget ? "border-red-500" : ""}`}
                  />
                </div>
                {errors.budget && (
                  <p className="text-sm text-red-600">{errors.budget}</p>
                )}
                <p className="text-xs text-gray-500">
                  {t("Annual budget allocation for this department")}
                </p>
              </div>
            </div>

            {/* Department Preview */}
            <div className="p-4 bg-gray-50 rounded-lg">
              <h4 className="font-medium mb-3">{t("Department Preview")}</h4>
              <div className="space-y-2">
                <div className="flex items-center space-x-2">
                  <Badge variant="outline">{formData.code || "CODE"}</Badge>
                  <span className="font-medium">
                    {formData.name || t("Department Name")}
                  </span>
                  <Badge
                    className={
                      formData.status === "active"
                        ? "bg-green-100 text-green-800"
                        : "bg-red-100 text-red-800"
                    }
                  >
                    {formData.status}
                  </Badge>
                </div>
                <p className="text-sm text-gray-600">
                                      {formData.description ||
                      t("Department description will appear here...")}
                </p>
                <div className="text-sm text-gray-500">
                  <p>{t("Head:")}: {formData.head || t("Department Head")}</p>
                  <p>{t("Location:")}: {formData.location || t("Department Location")}</p>
                  <p>{t("Staff:")}: {formData.staffCount} {t("members")}</p>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>

        {/* Footer Actions */}
        <div className="flex justify-end space-x-3 pt-4 border-t">
          <Button variant="outline" onClick={handleClose}>
            <X className="h-4 w-4 mr-2" />
            {t("Cancel")}
          </Button>
          <Button onClick={handleSubmit}>
            <Save className="h-4 w-4 mr-2" />
            {t("Add Department")}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default AddDepartmentModal;
